# Generated by Django 5.2.8 on 2026-04-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'event_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('Management_id', models.AutoField(primary_key=True, serialize=False)),
                ('Management_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
            options={
                'db_table': 'core_management',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_rollNo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_rollNo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admin', to='dashboard.management')),
            ],
            options={
                'db_table': 'organization_admin',
            },
        ),
    ]
