# Generated by Django 5.2.8 on 2026-05-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_eventadvisor_replace_event_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
