# Generated by Django 5.2.8 on 2026-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_meetingrequest_organization_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
